### ISSUE TITLE
Replace 'RPLACEHOLDER' with non-breaking space so it is invisible even when hidden characters shown.

### ISSUE THREAD

**Issue by MattCowgill** [noamross/redoc#49]
Thanks so much for this wonderful package, it's extremely useful.

When I try to knit to redoc, I get text reading 'RPLACEHOLDER' in place of R output. For example, here is the knitted skeleton redoc document:
<img width="556" alt="Screen Shot 2019-06-12 at 10 01 06 am" src="https://user-images.githubusercontent.com/8002951/59314531-0929f200-8cf9-11e9-80c0-f19e468dbeb9.png">
<img width="705" alt="Screen Shot 2019-06-12 at 10 01 12 am" src="https://user-images.githubusercontent.com/8002951/59314532-0929f200-8cf9-11e9-82b0-f4fd50015172.png">

This is a mystery to me, as it is only happening on one of my computers (macOS 10.14.3). It's running Pandoc version 2.7.2, RStudio 1.2.1335, rmarkdown 1.13.1.

**Comment by noamross** [comment]
`RPLACEHOLDER` is used as, well, a placeholder for the location in the document for code that has no output, like the `include=FALSE` chunk or the HTML comment. It is stored as _hidden text_, so I think in this case you have viewing hidden text turned on in Word, (under Word > Preferences... > View > Show Non-Printing Characters > Hidden Text).

But of course this means that a collaborator who has this turned on may see `RPLACEHOLDER` and this would be undesirable.  So I may see if I can hide it further by using a non-breaking space or other near-invisible character instead of `RPLACEHOLDER`.

**Comment by MattCowgill** [comment]
OK, thanks for clarifying, sorry for the silly question.

**Comment by noamross** [comment]
Not silly at all! It's helpful to see what snafus people run into and what in the package can be confusing.
